In [31]:
import numpy as np

A =  np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# 2. Matrix operations

In [32]:
'''element-wise'''
A_exp = A ** 2
# print(A_exp)

'''invert'''
A_inv = np.linalg.inv(A)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# 3. Array structure / shape operations 

## concat

In [33]:
"""concatenate"""
'''
can have multiple arrays in the tuple.
only the dimension to concat can be diff
'''
print("concat:")
result_vertical = np.concatenate((array1, array2), axis=0)
result_horizontal = np.concatenate((array1, array2), axis=1)

print("result_vertical:\n", result_vertical, "\n")
print("result_horizontal:\n", result_horizontal, "\n")


"""stack"""
'''vertically stack'''
print("stack")
result_vstack = np.vstack((array1, array2))
print("result_vstack:\n", result_vstack, "\n")

'''horizontally stack'''
result_hstack = np.hstack((array1, array2))
print("result_hstack:\n", result_hstack, "\n")

concat:
result_vertical:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

result_horizontal:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 

stack
result_vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

result_hstack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 



# Others

In [34]:
'''sort'''
a = np.array([3, 1, 2])
print(np.sort(a))
print(np.argsort(a))
print(a[np.argsort(a)])

[1 2 3]
[1 2 0]
[1 2 3]


In [35]:
'''plot related'''
xs = np.linspace(0, 10, 100)
# print(xs)

: 